entVirSintacticoV/proyectoHolaMundo/about/urls.py
from django.urls import path
from .views import about

app_name = 'about'

urlpatterns = [
    path("mi-empresa/", about, name="about")
]

entVirSintacticoV/proyectoHolaMundo/grafo/urls.py
from django.urls import path
from .views import calculaGrafo, umbral
from .views import procesamiento
#from .import views


urlpatterns = [
    path("mi-grafo/",calculaGrafo, name="grafo"),
    path("procesamiento/",procesamiento, name="procesamiento"),
    path("umb/",umbral, name="umbral"),

    
]

entVirSintacticoV/proyectoHolaMundo/homes/urls.py
from django.urls.conf import path
from .import views

urlpatterns = [
    path('',views.micasa,name='homes'),
   

]

entVirSintacticoV/proyectoHolaMundo/proyectoHolaMundo/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('homes.urls')),
    path('',include('sintactico.urls')),
    path('',include('about.urls')),
    path('',include('grafo.urls')),
]

entVirSintacticoV/proyectoHolaMundo/sintactico/urls.py
from django.urls import path
from .views import principal

app_name = 'sintactico'

urlpatterns = [
    path("sintactico-estructural-patrones/", principal, name="patrones")
    
]

entVirSintacticoV/proyectoHolaMundo/about/models.py
from django.db import models

# Create your models here.

entVirSintacticoV/proyectoHolaMundo/grafo/models.py
from django.db import models

# Create your models here.

entVirSintacticoV/proyectoHolaMundo/homes/models.py
from django.db import models

# Create your models here.
class paciente(models.Model):
    nombre= models.CharField( max_length=50)
    class Meta:
        verbose_name = ("paciente")
        verbose_name_plural = ("pacientes")

    def __str__(self):
        return self.nombre

    #def get_absolute_url(self):
      #  return reverse("_detail", kwargs={"pk": self.pk})


class tessiu(models.Model):

    temperature= models.FloatField(verbose_name="Temperatura:)") 
    color = models.FloatField()
    inflamation=models.FloatField(verbose_name="Inflamacion")
    nombre=models.ForeignKey(paciente, on_delete=models.CASCADE,blank=True, null=True)
    
    class Meta:
        verbose_name = "Tejido"
        verbose_name_plural = "Tejidos"

    def __str__(self):
        return 'temperatura: '+ str(self.temperature)+ 'Color: ' + str(self.color)

    #def get_absolute_url(self):
     #   return reverse("Tejido_detail", kwargs={"pk": self.pk})

entVirSintacticoV/proyectoHolaMundo/servicios/models.py
from django.db import models

# Create your models here.

entVirSintacticoV/proyectoHolaMundo/sintactico/models.py
from django.db import models

# Create your models here.

entVirSintacticoV/proyectoHolaMundo/about/views.py
#from django.http.response import HttpResponse
from django.shortcuts import render

# Create your views here.
def about(request):
    resultado= mifuncion(request)
    template_name='about/about.html' 
    return render(request,template_name,{"nombreusuario": resultado,"edad":21})

def mifuncion(args):
    return 'isaac'
"""
textHTML=
  
<h1>Hola Mundo</h1>
<ul>
<li>Donde 
<li>La fiesta
</ul>
    
    
"""
    

entVirSintacticoV/proyectoHolaMundo/grafo/views.py
from homes.models import tessiu
from django.shortcuts import render
import math

distancias = []

def creaMatriz(n,m):
    matriz = []
    for i in range(n):
        a = [0]*m
        matriz.append(a)
    return matriz

def calculaGrafo(request):
    tejidos = []
    

    Lista = tessiu.objects.get_queryset()
    for elemento in Lista:
        tejidos.append([elemento.temperature, elemento.color, elemento.inflamation])

    global distancias 
    distancias = creaMatriz(len(tejidos), len(tejidos))
    for i in range(len(tejidos)):
        for j in range(i, len(tejidos)):         
            distan = math.dist(tejidos[i], tejidos[j])
            distancias[i][j] = distan
            distancias[j][i] = distan

    diccionario={"distancias": distancias}
    return render(request,"grafo.html",diccionario)


def umbral(request):
    umbral = request.POST['umbral']
    print(umbral)
    procesado = []
    for i in range(len(distancias)):
        for j in range(i, len(distancias)):
            if distancias[i][j] == 0:
                procesado.append([i,j,distancias[i][j], "Si"])
            elif distancias[i][j] > float(umbral):
                procesado.append([i,j,distancias[i][j], "No"])
            else:
                procesado.append([i,j,distancias[i][j], "Si"])
    #print("procesado es: ",procesado)

    diccionario = {"umbrales" : procesado}
    return render(request, "umbral.html", diccionario)

def procesamiento(request):
    print(request.POST['umbral'])
    diccionario = {"umbrales" : umbral}
    return render(request, "umbral.html", diccionario)
    

entVirSintacticoV/proyectoHolaMundo/homes/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import tessiu
# Create your views here.

def micasa(request):
    Lista=tessiu.objects.get_queryset()

    L1,L2= procesamientoLista(Lista)
    template_name='homes/homes.html'
    mislistas=[Lista,L1,L2]
    diccionario={'l':Lista,"otra":"informacion","Lista1":L1,"Lista2":L2,"mislistas":mislistas}
    return render(request,template_name,diccionario)

def procesamientoLista(L):
    listaColorMayor39=[]
    listaColorMenor39=[]
    for i in L: 
        if i.color > 39:
            listaColorMayor39.append(i)
        else:
            listaColorMenor39.append(i)
    
    return listaColorMayor39,listaColorMenor39

entVirSintacticoV/proyectoHolaMundo/servicios/views.py
from django.shortcuts import render

# Create your views here.

entVirSintacticoV/proyectoHolaMundo/sintactico/views.py
from django.http.response import HttpResponse
from django.shortcuts import render 

# Create your views here.

def principal(request):
    template_name="sintactico/sintactico.html"
    diccionarioDeContexto1={'lista':[1,2,3,4,5]}
    return render(request,template_name,diccionarioDeContexto1)
#def principal(request):
#    return HttpResponse('<h1>Sintactico Estructural</h1>')

entVirSintacticoV/proyectoHolaMundo/about/templates/about/about.html
<body  style= "background-color:rgba(202, 120, 191, 0.842)">
    <ul>
       <li class="horizontal"><a href="{% url 'homes' %}" class="button">Home</a> </li>
       <li class="horizontal"><a href="{% url 'sintactico:patrones' %}"class="button">Ayuda y Capacitación</a></li>
       <li class="horizontal"><a href="{% url 'about:about' %}"class="button">Conocenos</a></li>
       <li class="horizontal"><a href="{% url 'grafo' %}"class="button">Grafo</a></li>
   
    </ul>
<div>
    <h4 align=center><b> CONOCENOS </b></h4>
    <p align=center>El objetivo del cribado es identificar a las personas que podrían tener una enfermedad, mediante la realización de pruebas para detectar signos de enfermedad y poder tratar con mayor rapidez y eficacia el problema.</p>
    <div>
        <p>Hay muchos tipos de pruebas las cuales te puedes realizar. Como por ejemplo:</p>

        <ul>
          <li> <b> Ultrasonido mamario:</b></li> <p> Máquina que usa ondas de sonido para producir imágenes, llamadas sonogramas, de áreas dentro de la mama.</p>
          <li> <b> Mamografía de diagnóstico:</b></li> <p> Si usted tiene algún problema en la mama —como un bulto— o si un área de la mama se ve anormal en una mamografía de detección, el médico puede indicarle que se haga una mamografía diagnóstica. Esta es una radiografía más detallada de la mama.</p>
          <li> <b> Imagen por resonancia magnética (IRM) de las mamas.:</b></li><p> Un tipo de escaneo del cuerpo que usa un imán conectado a una computadora. La resonancia magnética  creará imágenes detalladas de áreas dentro de la mama.</p>
            <li> <b> Biopsia:</b></li> <p> . Esta es una prueba en la que se extirpa tejido o se saca líquido de la mama para estudiarse bajo el microscopio o para hacer más pruebas. Existen distintos tipos de biopsias (por ejemplo, aspiración con aguja fina, biopsia con aguja gruesa o biopsia abierta).</p>
        </p>
           
        </ul>
    </div>
    <style>

        .button {
          background-color: #701e51;
          border: 5px;;
          color: white;
          padding: 5px 5px;
          text-align: center;
          text-decoration: none;
          display: inline-block;
          font-size: 20px;
          margin: 4px 2px;
          cursor: pointer;
        }
    
        .horizontal{
            display: block;
            float: left;
            padding: 2px;
            
        }
      </style>

entVirSintacticoV/proyectoHolaMundo/grafo/templates/grafo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ISI pagina principal</title>

    
</head>
<body  style= "background-color:rgba(202, 120, 191, 0.842)">
    <ul>
       <li class="horizontal"><a href="{% url 'homes' %}" class="button">Home</a> </li>
       <li class="horizontal"><a href="{% url 'sintactico:patrones' %}"class="button">Ayuda y Capacitación</a></li>
       <li class="horizontal"><a href="{% url 'about:about' %}"class="button">Conocenos</a></li>
       <li class="horizontal"><a href="{% url 'grafo' %}"class="button">Grafo</a></li>
    <form action="{%url 'umbral'%}" method="POST">
        {%csrf_token%}
        <label for="umbral">UMBRAL</label>
        <input type="text" name="umbral" id="umbral">
    <button type="submit" name="miboton" class="button">Iniciar Procesamiento</button>

    </form>

    {% block blockname1 %}
    
    {% endblock blockname1 %}

    <table class="horizontal">
        <tbody>
            {% for distancia in distancias%}
            <tr>
                {% for d in distancia  %}
                <td style="border:2px solid #701e55;">{{d}}</td>
                {% endfor %}
                
            </tr>
            {% endfor %} 

        </tbody>
    </table>


<!--separar-->

    {% block blockname %}
  
{% endblock blockname %}



{% block footers %}
   
{% endblock footers %}

</body>
<style>
    .button {
      background-color: #701e51;
      border: 5px;;
      color: white;
      padding: 5px 5px;
      text-align: center;
      text-decoration: none;
      display: inline-block;
      font-size: 20px;
      margin: 4px 2px;
      cursor: pointer;
    }

    .horizontal{
        display: block;
        float: left;
        padding: 2px;
        
    }
  </style>

</html>

entVirSintacticoV/proyectoHolaMundo/grafo/templates/umbral.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ISI pagina principal</title>

    
</head>
<body  style= "background-color:rgba(202, 120, 191, 0.842)">
    <ul>
       <li class="horizontal"><a href="{% url 'homes' %}" class="button">Home</a> </li>
       <li class="horizontal"><a href="{% url 'sintactico:patrones' %}"class="button">Ayuda y Capacitación</a></li>
       <li class="horizontal"><a href="{% url 'about:about' %}"class="button">Conocenos</a></li>
       <li class="horizontal"><a href="{% url 'grafo' %}"class="button">Grafo</a></li>
    </ul>
   
    {% block blockname1 %}
    
    {% endblock blockname1 %}

    <table class="horizontal">
        <tbody>
            {% for umb in umbrales%}
            <tr>
                {% for u in umb  %}
                <td style="border:2px solid #701e55;">{{u}}</td>
                {% endfor %}
                
            </tr>
            {% endfor %} 

        </tbody>
    </table>


<!--separar-->

    {% block blockname %}
  
{% endblock blockname %}



{% block footers %}
   
{% endblock footers %}

</body>
<style>
    .button {
      background-color: #701e51;
      border: 5px;;
      color: white;
      padding: 5px 5px;
      text-align: center;
      text-decoration: none;
      display: inline-block;
      font-size: 20px;
      margin: 4px 2px;
      cursor: pointer;
    }

    .horizontal{
        display: block;
        float: left;
        padding: 2px;
        
    }
  </style>

</html>

entVirSintacticoV/proyectoHolaMundo/homes/templates/homes/homes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ISI pagina principal</title>

    
</head>
<body  style= "background-color:rgba(202, 120, 191, 0.842)">
    <ul>
       <li class="horizontal"><a href="{% url 'homes' %}" class="button">Home</a> </li>
       <li class="horizontal"><a href="{% url 'sintactico:patrones' %}"class="button">Ayuda y Capacitación</a></li>
       <li class="horizontal"><a href="{% url 'about:about' %}"class="button">Conocenos</a></li>
       <li class="horizontal"><a href="{% url 'grafo' %}"class="button">Grafo</a></li>
   
    </ul>
    
       
    </form>
   
    <div class="wave" style="height: 150px;overflow: hidden;"><svq viewBox="0 0 500 150"preserveAspectRatio="none"
        style="height: 100%;width:100%;"><path d="M0.00,49.98C150.00,150.00 349.20,-50.00 500.00, 49.98 L500.00,
        150.00 L0.00,150.00 Z"style="stroke:none;fill:#f0f;"></path></svq></div>
    

    <div align=right>
    
        Información general sobre el Cáncer de Mama
        <ul>
            <li>El cáncer de mama es una enfermedad por la que se forman células malignas (cancerosas) en los tejidos de la mama.</li>
            <li>El cáncer de mama es la segunda causa principal de muerte por cáncer en las mujeres en los Estados Unidos.</li>
            <li>Varios factores aumentan o disminuyen el riesgo de cáncer de mama.</li>
        </ul>
    </div>
    <div>
        <p>
             Los científicos tratan de entender mejor quiénes tienen más probabilidades de enfermar de ciertos tipos de cáncer. Por ejemplo, analizan la edad de la persona, sus antecedentes familiares y ciertas exposiciones a lo largo de su vida. Esta información ayuda a los médicos
             a recomendar quién se debe someter a los exámenes de detección del cáncer, qué pruebas se deben utilizar y con qué frecuencia se deben realizar.    
        </p></div>
       
    <div align=center>
        ¿Qué son los exámenes de detección?</div>
    <div align=right>
        <p >
            Los exámenes de detección verifican la presencia de signos de enfermedad, <br>
            como el cáncer de mama, antes de que la persona tenga síntomas. El propósito<br>
            de los exámenes de detección es encontrar el cáncer en un estadio más temprano<br>
            Los exámenes de detección verifican la presencia de signos de enfermedad,<br>
            cuando se puede tratar y quizá se cure. A veces, durante los exámenes de <br>
            detección se encuentra cáncer que es muy pequeño o de crecimiento muy lento.<br>
        </p></div>
    
    <img src="https://picsum.photos/id/237/200/300" alt="My image">
   
    
    </body>
   
<style>
    .button {
      background-color: #701e51;
      border: 5px;;
      color: white;
      padding: 5px 5px;
      text-align: center;
      text-decoration: none;
      display: inline-block;
      font-size: 20px;
      margin: 4px 2px;
      cursor: pointer;
    }

    .horizontal{
        display: block;
        float: left;
        padding: 2px;
        
    }
  </style>

</html>

entVirSintacticoV/proyectoHolaMundo/sintactico/templates/sintactico/sintactico.html
<body  style= "background-color:rgba(202, 120, 191, 0.842)">
    <ul>
       <li class="horizontal"><a href="{% url 'homes' %}" class="button">Home</a> </li>
       <li class="horizontal"><a href="{% url 'sintactico:patrones' %}"class="button">Ayuda y Capacitación</a></li>
       <li class="horizontal"><a href="{% url 'about:about' %}"class="button">Conocenos</a></li>
       <li class="horizontal"><a href="{% url 'grafo' %}"class="button">Grafo</a></li>
   
    </ul>
 <div>
    <img>
<div>
<h4 align=center><b> Signos y síntomas  </b></h4>
<p>El síntoma más común del cáncer de seno es la presencia de un nódulo o masa que antes no estaba, pero también es posible que se generen otros síntomas. Es importante que cualquier cambio que note en sus senos sea revisado por su médico.</p>
</div>
</div>
<div>
    <p>Varios aspectos pueden afectar la capacidad de la mamografía para detectar (encontrar) el cáncer de mama:</p>
    <ul>
      <li>  Edad y peso del paciente.</li>
      <li>  Tamaño y tipo del tumor.</li>
      <li>  Si el tumor se ha formado en la mama.</li>
      <li>  Sensibilidad del tejido de la mama a las hormonas.</li>
      <li>  Densidad del tejido de la mama.</li>
      <li>  Momento en que se hace la mamografía dentro del ciclo menstrual de la mujer.</li>
      <li>  Calidad de la imagen de la mamografía.</li>
      <li>  Habilidad del radiólogo para interpretar la imagen.</li>

        <p> Las imágenes por resonancia magnética se utilizan para examinar a mujeres con riesgo alto de cáncer de mama.</p>
           <p>Las mujeres de 50 a 69 años que se someten a mamografías de detección tienen menos probabilidades de morir por este cáncer que quienes no lo hacen.
            </p>
    </ul>
    <img src="https://picsum.photos/seed/picsum/200/300" alt="My image">
    
</div>

<style>

    .button {
      background-color: #701e51;
      border: 5px;;
      color: white;
      padding: 5px 5px;
      text-align: center;
      text-decoration: none;
      display: inline-block;
      font-size: 20px;
      margin: 4px 2px;
      cursor: pointer;
    }

    .horizontal{
        display: block;
        float: left;
        padding: 2px;
        
    }
  </style>

    